### ISSUE TITLE
Things todo

### ISSUE THREAD

**Issue by Nerajno** [Gerdeth/More-Movies#1]
### Todos

- [ ] Create a good ReadMe
- [ ] Hide api keys
- [ ] Hide api~addresses/ paths
- [ ] new color scheme
- [ ] add back to portfoli btn or back to github
